[package]
name = "tracktree"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
burn = "0.20.1"
burn-ndarray = "0.20.1"
plotters = "0.3.7"
rand = "0.9.2"
realfft = "3.5.0"
rustfft = "6.4.1"
